
services:

  # Web Application Service
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  # Database Service 
  db:
    image: postgres:15  # Use a specific, stable version of Postgres
    container_name: postgres_db  # Name the container for easier reference
    restart: always  # Automatically restart the container if it crashes
    environment:
      POSTGRES_USER: DatabaseUsername
      POSTGRES_PASSWORD: DatabasePassword 
      POSTGRES_DB: DegreeTrackingDatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent storage for database data

# Define Docker Volumes for Persistent Data Storage
volumes:
  postgres_data:

