# Generated by Django 5.1.6 on 2025-04-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('prerequisite', models.CharField(default='', max_length=200)),
                ('co_requisite', models.CharField(default='', max_length=200)),
                ('credits', models.TextField(default='')),
                ('CoreRequirement', models.TextField(default='')),
                ('course_offered', models.CharField(default='', max_length=200)),
                ('course_type', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EnrolledCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('progress', models.CharField(default='', max_length=100)),
                ('semesterEnrolled', models.CharField(default='', max_length=100)),
                ('gpa', models.CharField(default='In Progress', max_length=10)),
                ('credits', models.CharField(default='0', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MajorReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('prerequisite', models.CharField(default='', max_length=200)),
                ('co_requisite', models.CharField(default='', max_length=200)),
                ('credits', models.TextField(default='')),
                ('CoreRequirement', models.TextField(default='')),
                ('course_offered', models.CharField(default='', max_length=200)),
                ('course_type', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('firstName', models.CharField(default='', max_length=30)),
                ('lastName', models.CharField(default='', max_length=30)),
                ('studentEmail', models.CharField(default='', max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
