# Generated by Django 5.1.6 on 2025-04-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_student_id_alter_student_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='firstName',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='lastName',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='studentEmail',
            field=models.CharField(default='', max_length=254, unique=True),
        ),
    ]
