# Generated by Django 5.1.6 on 2025-03-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_majorreq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorreq',
            name='course_offered',
            field=models.TextField(),
        ),
    ]
