# Generated by Django 5.1.6 on 2025-04-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_majorreq_corerequirement_majorreq_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorreq',
            name='co_requisite',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='majorreq',
            name='credits',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='majorreq',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='majorreq',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='majorreq',
            name='prerequisite',
            field=models.CharField(default='', max_length=200),
        ),
    ]
