# Generated by Django 5.1.6 on 2025-04-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_majorreq_co_requisite_alter_majorreq_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorreq',
            name='CoreRequirement',
            field=models.TextField(default=''),
        ),
    ]
