# Generated by Django 5.1.6 on 2025-04-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_majorreq_corerequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('progress', models.CharField(default='', max_length=100)),
                ('semesterEnrolled', models.CharField(default='', max_length=100)),
                ('gpa', models.CharField(default='In Progress', max_length=10)),
            ],
        ),
    ]
