# Generated by Django 5.1.6 on 2025-04-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_enrolledcourses'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('prerequisite', models.CharField(default='', max_length=200)),
                ('co_requisite', models.CharField(default='', max_length=200)),
                ('credits', models.TextField(default='')),
                ('CoreRequirement', models.TextField(default='')),
                ('course_offered', models.CharField(default='', max_length=200)),
                ('course_type', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
