# Generated by Django 5.1.6 on 2025-04-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_enrolledcourses'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledcourses',
            name='credits',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
